name: Build for Devices

on:
  pull_request:
    paths:
      - "Sources/**"
      - "Package.swift"
      - ".github/workflows/build-devices.yml"

  push:
    branches:
      - master

  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  device-build:
    runs-on: macos-15
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS
            archs: "arm64 arm64e"
          - platform: watchOS
            archs: "arm64_32"
          - platform: tvOS
            archs: "arm64"
          - platform: macOS
            archs: "arm64 x86_64"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Latest Stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Platform SDK
        if: matrix.platform != 'macOS'
        continue-on-error: true
        run: |
          xcodebuild -downloadPlatform ${{ matrix.platform }} -architectureVariant universal

      - name: Build for Device Platform
        run: |
          xcodebuild build \
            -workspace ".swiftpm/xcode/package.xcworkspace" \
            -scheme "KSCrash-Package" \
            -destination "generic/platform=${{ matrix.platform }}" \
            -configuration Release \
            ARCHS="${{ matrix.archs }}"
